// <auto-generated />
using System;
using CTMS.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223085156_DataSeedingForEmployeeAndDepartment")]
    partial class DataSeedingForEmployeeAndDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CTMS.Repository.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfEstablishment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfEstablishment = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Produce Valuable Software",
                            Location = "3rd-floor",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            DateOfEstablishment = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Produce Valuable Software",
                            Location = "3rd-floor",
                            Name = "Salse"
                        },
                        new
                        {
                            Id = 3,
                            DateOfEstablishment = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Produce Valuable Software",
                            Location = "3rd-floor",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            DateOfEstablishment = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Produce Valuable Software",
                            Location = "3rd-floor",
                            Name = "QA"
                        },
                        new
                        {
                            Id = 5,
                            DateOfEstablishment = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Produce Valuable Software",
                            Location = "3rd-floor",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("CTMS.Repository.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnrolled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTrainer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("YearsOfExperties")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "khambhat",
                            DepartmentId = 1,
                            Designation = "Software Developer",
                            Email = "raj123@gmail.com",
                            IsEnrolled = false,
                            IsTrainer = false,
                            Name = "Raj Rana",
                            PhoneNumber = "7046192318",
                            Salary = 40000m,
                            YearsOfExperties = 3
                        },
                        new
                        {
                            Id = 2,
                            Address = "Lodhva",
                            DepartmentId = 1,
                            Designation = "Software Developer",
                            Email = "ravi123@gmail.com",
                            IsEnrolled = false,
                            IsTrainer = false,
                            Name = "Vadher Ravi",
                            PhoneNumber = "8046192318",
                            Salary = 40000m,
                            YearsOfExperties = 3
                        },
                        new
                        {
                            Id = 3,
                            Address = "Vadhvan",
                            DepartmentId = 2,
                            Designation = "Salse Executive",
                            Email = "rakesh123@gmail.com",
                            IsEnrolled = false,
                            IsTrainer = false,
                            Name = "Rakesh Parmar",
                            PhoneNumber = "8146192318",
                            Salary = 30000m,
                            YearsOfExperties = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "Gondal",
                            DepartmentId = 3,
                            Designation = "Salse Executive",
                            Email = "yashraj123@gmail.com",
                            IsEnrolled = false,
                            IsTrainer = false,
                            Name = "Yashraj Vaghela",
                            PhoneNumber = "7746192318",
                            Salary = 20000m,
                            YearsOfExperties = 2
                        },
                        new
                        {
                            Id = 5,
                            Address = "Rajkot",
                            DepartmentId = 3,
                            Designation = "Marketing Intern",
                            Email = "akash123@gmail.com",
                            IsEnrolled = false,
                            IsTrainer = false,
                            Name = "Akash Pateliya",
                            PhoneNumber = "7846192318",
                            Salary = 5000m,
                            YearsOfExperties = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nadiyad",
                            DepartmentId = 4,
                            Designation = "QA Developer",
                            Email = "mehul123@gmail.com",
                            IsEnrolled = false,
                            IsTrainer = false,
                            Name = "Mehul Prajapati",
                            PhoneNumber = "8086192318",
                            Salary = 40000m,
                            YearsOfExperties = 3
                        },
                        new
                        {
                            Id = 7,
                            Address = "Anand",
                            DepartmentId = 5,
                            Designation = "Accountent",
                            Email = "sujal123@gmail.com",
                            IsEnrolled = false,
                            IsTrainer = false,
                            Name = "Sujal Prajapati",
                            PhoneNumber = "7946192318",
                            Salary = 50000m,
                            YearsOfExperties = 4
                        });
                });

            modelBuilder.Entity("CTMS.Repository.Entities.EnrolledEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EnrolledEmployees", (string)null);
                });

            modelBuilder.Entity("CTMS.Repository.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrolledEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrolledEmployeeId");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("CTMS.Repository.Entities.TrainerEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("TrainerEmployees", (string)null);
                });

            modelBuilder.Entity("CTMS.Repository.Entities.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TrainingPrograms", (string)null);
                });

            modelBuilder.Entity("EnrolledEmployeeTrainingProgram", b =>
                {
                    b.Property<int>("EnrolledEmployeesId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramsId")
                        .HasColumnType("int");

                    b.HasKey("EnrolledEmployeesId", "TrainingProgramsId");

                    b.HasIndex("TrainingProgramsId");

                    b.ToTable("EnrolledEmployee_IN_TrainingPrograms", (string)null);
                });

            modelBuilder.Entity("TrainerEmployeeTrainingProgram", b =>
                {
                    b.Property<int>("TrainerEmployeesId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramsId")
                        .HasColumnType("int");

                    b.HasKey("TrainerEmployeesId", "TrainingProgramsId");

                    b.HasIndex("TrainingProgramsId");

                    b.ToTable("TrainingPrograms_With_TrainerEmployee", (string)null);
                });

            modelBuilder.Entity("CTMS.Repository.Entities.Employee", b =>
                {
                    b.HasOne("CTMS.Repository.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CTMS.Repository.Entities.EnrolledEmployee", b =>
                {
                    b.HasOne("CTMS.Repository.Entities.Employee", "Employee")
                        .WithOne("EnrolledEmployee")
                        .HasForeignKey("CTMS.Repository.Entities.EnrolledEmployee", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CTMS.Repository.Entities.Score", b =>
                {
                    b.HasOne("CTMS.Repository.Entities.EnrolledEmployee", "enrolledEmployee")
                        .WithMany("Scores")
                        .HasForeignKey("EnrolledEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTMS.Repository.Entities.TrainingProgram", "trainingProgram")
                        .WithMany("Scores")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("enrolledEmployee");

                    b.Navigation("trainingProgram");
                });

            modelBuilder.Entity("CTMS.Repository.Entities.TrainerEmployee", b =>
                {
                    b.HasOne("CTMS.Repository.Entities.Employee", "Employee")
                        .WithOne("TrainerEmployee")
                        .HasForeignKey("CTMS.Repository.Entities.TrainerEmployee", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EnrolledEmployeeTrainingProgram", b =>
                {
                    b.HasOne("CTMS.Repository.Entities.EnrolledEmployee", null)
                        .WithMany()
                        .HasForeignKey("EnrolledEmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTMS.Repository.Entities.TrainingProgram", null)
                        .WithMany()
                        .HasForeignKey("TrainingProgramsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainerEmployeeTrainingProgram", b =>
                {
                    b.HasOne("CTMS.Repository.Entities.TrainerEmployee", null)
                        .WithMany()
                        .HasForeignKey("TrainerEmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTMS.Repository.Entities.TrainingProgram", null)
                        .WithMany()
                        .HasForeignKey("TrainingProgramsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CTMS.Repository.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CTMS.Repository.Entities.Employee", b =>
                {
                    b.Navigation("EnrolledEmployee")
                        .IsRequired();

                    b.Navigation("TrainerEmployee")
                        .IsRequired();
                });

            modelBuilder.Entity("CTMS.Repository.Entities.EnrolledEmployee", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("CTMS.Repository.Entities.TrainingProgram", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
